import { type Accent, accentBg, cn } from '@shimanto/ui';
import type { Playbook } from '@/content/playbooks';
import { templateHref } from '@/lib/playbooks';

/** A playbook's templates as download rows (plain files, generated by the template route). */
export function TemplateDownloads({ playbook, tone }: { playbook: Playbook; tone: Accent }) {
  return (
    <ul className="border-ink/10 border-b">
      {playbook.templates.map((template) => (
        <li key={template.file}>
          <a
            href={templateHref(playbook, template)}
            download={template.file}
            className="group border-ink/10 flex items-center gap-5 border-t py-5"
          >
            <span
              aria-hidden="true"
              className={cn(
                'text-on-world grid h-12 w-10 shrink-0 place-items-center rounded-md font-mono text-[10px] font-semibold uppercase',
                accentBg[tone],
              )}
            >
              .{template.file.split('.').pop()}
            </span>
            <span className="min-w-0 flex-1">
              <span className="block text-lg font-medium group-hover:underline">
                {template.name}
              </span>
              <span className="text-ink-soft block">{template.description}</span>
            </span>
            <span className="text-ink-soft group-hover:text-ink shrink-0 text-sm font-medium">
              Download ↓<span className="sr-only"> {template.file}</span>
            </span>
          </a>
        </li>
      ))}
    </ul>
  );
}
