// Generated by Publishing OS. Lists the case studies in this folder; regenerated on every publish.
import type { CaseStudyReport } from '../../case-study-report';

export const publishingOsCaseStudies: CaseStudyReport[] = [];
