// Generated by Publishing OS. Lists the posts in ./posts; regenerated on every publish.
import type { Entry } from '../catalog';
import { post as p0_from_question_to_content_brief } from './posts/from-question-to-content-brief';
import { post as p1_internal_links_how_a_site_starts_to_comp } from './posts/internal-links-how-a-site-starts-to-compound';
import { post as p2_publish_measure_repeat } from './posts/publish-measure-repeat';
import { post as p3_publishing_system_not_content_calendar } from './posts/publishing-system-not-content-calendar';
import { post as p4_seo_without_the_theatre } from './posts/seo-without-the-theatre';
import { post as p5_writing_with_ai_without_losing_your_voic } from './posts/writing-with-ai-without-losing-your-voice';

export const publishingOsPosts: Entry[] = [
  p0_from_question_to_content_brief,
  p1_internal_links_how_a_site_starts_to_comp,
  p2_publish_measure_repeat,
  p3_publishing_system_not_content_calendar,
  p4_seo_without_the_theatre,
  p5_writing_with_ai_without_losing_your_voic,
];

/** Social cover images for these posts (public/ paths). */
export const publishingOsCovers: Record<
  string,
  { src: string; alt: string; width: number; height: number }
> = {
  'from-question-to-content-brief': {
    src: '/blog/covers/from-question-to-content-brief.png',
    alt: "Cover for “From question to content brief”: a Research panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
  'internal-links-how-a-site-starts-to-compound': {
    src: '/blog/covers/internal-links-how-a-site-starts-to-compound.png',
    alt: "Cover for “Internal links: how a site starts to compound”: a Technology panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
  'publish-measure-repeat': {
    src: '/blog/covers/publish-measure-repeat.png',
    alt: "Cover for “Publish, measure, repeat: closing the loop”: a Automation panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
  'publishing-system-not-content-calendar': {
    src: '/blog/covers/publishing-system-not-content-calendar.png',
    alt: "Cover for “Your website needs a publishing system, not a calendar”: a Founder notes panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
  'seo-without-the-theatre': {
    src: '/blog/covers/seo-without-the-theatre.png',
    alt: "Cover for “SEO without the theatre”: a Marketing panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
  'writing-with-ai-without-losing-your-voice': {
    src: '/blog/covers/writing-with-ai-without-losing-your-voice.png',
    alt: "Cover for “Writing with AI without losing your voice”: a AI panel in Shimanto's colours.",
    width: 1200,
    height: 630,
  },
};
