// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11pmy35488fd740cf8 · version 3 · 790372e2498d14ed
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'from-question-to-content-brief',
  title: 'From question to content brief',
  summary:
    "Most weak posts fail before the first sentence, so use a one-page content brief to decide the reader's question, your angle, your sources and what to cut.",
  category: 'Research',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "Most weak posts don't fail because of bad writing. They fail before the first sentence, because nobody decided what the piece was for. A content brief is that decision. It isn't paperwork. It's one page that answers four questions before you write anything: what is the reader really asking, what is your angle, which sources will you stand behind, and what are you leaving out?",
    },
    {
      type: 'h2',
      text: 'Most posts fail before the first sentence',
      id: 'most-posts-fail-before-the-first-sentence',
    },
    {
      type: 'p',
      text: "You'll know the symptoms. You stare at a blank page. The draft wanders off. The post ends up saying what every other post on the topic says. Or it reads well and still never answers what the reader asked.",
    },
    {
      type: 'p',
      text: "None of these is a writing problem. Each one is a missing decision showing up later, while you're trying to draft.",
    },
    {
      type: 'p',
      text: "So, do you need a brief if you write everything yourself? Yes. A brief isn't for handing work to someone else. It's for making the decision. When you're the writer, editor and publisher, you're the one who needs that decision made. Otherwise you end up making it halfway through paragraph four, which is the worst possible moment.",
    },
    {
      type: 'p',
      text: 'This is the "Decide" step of the publishing system. If you\'ve accepted that you should [own the house and rent the megaphone](/blog/own-the-house-rent-the-megaphone), the next question is what goes in the house. The answer should be deliberate, not whatever you felt like writing on a Tuesday.',
    },
    {
      type: 'h2',
      text: 'Start from a real question, not a keyword',
      id: 'start-from-a-real-question-not-a-keyword',
    },
    {
      type: 'p',
      text: "The best article ideas aren't brainstormed. Someone asked them.",
    },
    {
      type: 'p',
      text: 'They come from:',
    },
    {
      type: 'list',
      items: [
        'Customer emails',
        'Sales calls',
        'Support tickets',
        'Comments and DMs',
        "Anything you've explained more than twice",
      ],
    },
    {
      type: 'p',
      text: 'My opinion: one question from a real person beats ten topics you thought up yourself. The real question already has an audience. You know at least one person wants the answer, and others like them probably do too.',
    },
    {
      type: 'p',
      text: "Keep a running question log in one place. A note, a spreadsheet or a plain text file is fine. Every time someone asks you something worth answering, write it down in their words. This is the same move as in [systems beat motivation](/blog/systems-beat-motivation): you collect ideas by habit, not by waiting for inspiration. When it's time to write, you pick from the log. You never have to invent something on the spot.",
    },
    {
      type: 'p',
      text: "To turn a logged question into an article idea, do two things. First, rewrite it so it still sounds like the reader, not like a keyword. Second, ask yourself whether you can answer it from first-hand experience. If you can't, park it.",
    },
    {
      type: 'h3',
      text: 'Read the intent behind the question',
      id: 'read-the-intent-behind-the-question',
    },
    {
      type: 'p',
      text: 'What someone typed or asked and what they need answered aren\'t always the same thing. "What\'s a content brief?" usually means "how do I stop producing drafts that go nowhere?" Work out what they\'re trying to get done.',
    },
    {
      type: 'p',
      text: 'Write that job in one line:',
    },
    {
      type: 'p',
      text: 'After reading, they can ___.',
    },
    {
      type: 'p',
      text: "Then list the follow-up questions they'll have next. If they'll want a template, give them one. If they'll ask how long it takes, tell them. Google's [people-first content guidance](https://developers.google.com/search/docs/fundamentals/creating-helpful-content) asks whether a reader will leave \"feeling they've learned enough about a topic to help achieve their goal\". It also flags content that leaves readers \"feeling like they need to search again to get better information from other sources\" as a warning sign. Writing down the follow-ups is how you avoid that.",
    },
    {
      type: 'h2',
      text: 'Pick an angle you can defend',
      id: 'pick-an-angle-you-can-defend',
    },
    {
      type: 'p',
      text: "An angle isn't a clever headline. It's your opinion or your experience applied to the question.",
    },
    {
      type: 'p',
      text: "Here's a quick test. Skim what's already published on the topic and write down what everyone says. Then write the one thing you'd say differently, or the one thing you've actually done that they haven't. That's your angle.",
    },
    {
      type: 'p',
      text: 'This matters beyond style. Google\'s self-assessment questions ask whether content provides "insightful analysis or interesting information that is beyond the obvious". They also ask whether content that draws on other sources adds "substantial additional value and originality" rather than just rewriting those sources ([Google Search Central](https://developers.google.com/search/docs/fundamentals/creating-helpful-content)). A post with no angle is a rewrite with extra steps.',
    },
    {
      type: 'p',
      text: "If you can't write your angle in one sentence, you're not ready to write the post.",
    },
    {
      type: 'h2',
      text: "Choose sources you'll stand behind",
      id: 'choose-sources-you-ll-stand-behind',
    },
    {
      type: 'p',
      text: 'My rule is simple. If a fact isn\'t in my notes with a link next to it, it doesn\'t go in the post. No invented numbers, no half-remembered statistics, no quotes from "an expert".',
    },
    {
      type: 'p',
      text: 'Record each source as you find it, with three things:',
    },
    {
      type: 'list',
      items: ['The URL', "The specific claim you'll use from it", 'Why you trust it'],
    },
    {
      type: 'p',
      text: 'Your own experience counts as a source. Label it honestly as experience or opinion, not data. "In my experience" is a perfectly good basis for a claim. "Studies show" with no study behind it is not.',
    },
    {
      type: 'p',
      text: "How much research is enough? Set a time limit. In my opinion, an hour or so is plenty for most posts. Stop when you can answer the question and back up every factual claim. Don't wait until you've read everything, because you never will.",
    },
    {
      type: 'p',
      text: 'This is about trust as much as accuracy. Google lists "clear sourcing" among the things that make readers want to trust content ([Google Search Central](https://developers.google.com/search/docs/fundamentals/creating-helpful-content)). Readers notice when you\'ve done the work.',
    },
    {
      type: 'h2',
      text: 'Decide what to leave out',
      id: 'decide-what-to-leave-out',
    },
    {
      type: 'p',
      text: "The cut list is the most underrated part of a brief. It's how you keep a piece to one idea.",
    },
    {
      type: 'p',
      text: 'Leave out:',
    },
    {
      type: 'list',
      items: [
        "Anything you can't source",
        "Anything that answers a different reader's question",
        'Anything that only exists to make the post longer',
      ],
    },
    {
      type: 'p',
      text: "On that last point, Google says outright that it has no preferred word count ([Google Search Central](https://developers.google.com/search/docs/fundamentals/creating-helpful-content)). Padding doesn't help readers or rankings.",
    },
    {
      type: 'p',
      text: "Cutting doesn't mean throwing ideas away. Park the related topics as future posts and add them to your question log. Your leave-out list from today feeds next month's ideas.",
    },
    {
      type: 'p',
      text: 'For example, this piece deliberately leaves out SEO checks, internal linking and measurement. They matter, but each one has its own part of this series. Squeezing them in here would make all four worse.',
    },
    {
      type: 'h2',
      text: 'The one-page content brief template',
      id: 'the-one-page-content-brief-template',
    },
    {
      type: 'p',
      text: 'Copy this. Fill it in before your next post.',
    },
    {
      type: 'p',
      text: 'CONTENT BRIEF',
    },
    {
      type: 'p',
      text: 'Working title: Reader (who, in one line): The real question (in their words): Job to be done: After reading, they can… Follow-up questions to answer: - -',
    },
    {
      type: 'p',
      text: 'Angle (one sentence): What everyone else says:',
    },
    {
      type: 'p',
      text: 'Sources (URL — claim — why I trust it): - -',
    },
    {
      type: 'p',
      text: 'Experience I can draw on:',
    },
    {
      type: 'p',
      text: 'Leave out / park for later: - -',
    },
    {
      type: 'p',
      text: "Internal links (where this connects on my site): Call to action: Success signal (what I'll check later): A brief should take less time than the first draft. If it doesn't, it's turned into paperwork, and the paperwork has become a way of putting off the writing.",
    },
    {
      type: 'callout',
      title: "One page or it isn't a decision",
      text: "If it doesn't fit on one page, you haven't decided yet. Cut until it does.",
      tone: 'build',
    },
    {
      type: 'h3',
      text: 'A brief is what you hand your AI teammate',
      id: 'a-brief-is-what-you-hand-your-ai-teammate',
    },
    {
      type: 'p',
      text: "If you draft with AI, the brief matters even more. A prompt with no brief behind it is the vending-machine model: you put in a topic, you get back something generic, and you're disappointed. I've written about why [AI works better as a teammate than a vending machine](/blog/ai-is-a-teammate-not-a-vending-machine), and the brief is the briefing.",
    },
    {
      type: 'p',
      text: 'It gives the model four things:',
    },
    {
      type: 'list',
      items: [
        'The real question',
        'The angle',
        "The facts it's allowed to use",
        'The limits it has to stay inside',
      ],
    },
    {
      type: 'p',
      text: "That's what stops a draft from wandering, and it's what stops the model from filling gaps with made-up claims. The brief decides what gets said. How it sounds, in your voice and not the model's, is the next part of this series.",
    },
    {
      type: 'h2',
      text: 'How the brief feeds the rest of the system',
      id: 'how-the-brief-feeds-the-rest-of-the-system',
    },
    {
      type: 'p',
      text: 'A good brief keeps paying off after the draft is done.',
    },
    {
      type: 'list',
      items: [
        'The real question and the job to be done are what your SEO checks test the finished post against.',
        'The internal links field gives you a starting point for linking.',
        "The success signal is what you'll measure later.",
      ],
    },
    {
      type: 'p',
      text: "One brief gives you one post. Keep the briefs and, over time, they become a map of what your site covers, what it doesn't, and which questions are still waiting in the log.",
    },
    {
      type: 'p',
      text: 'Remember what the brief is for, though. It exists to get a post out, not to put one off. Decide, then ship.',
    },
    {
      type: 'h2',
      text: 'Do this before your next post',
      id: 'do-this-before-your-next-post',
    },
    {
      type: 'list',
      items: [
        'Pick one real question someone asked you this week.',
        'Copy the template above and fill in the four core fields first: the question, the angle, the sources and the leave-outs.',
        'Give yourself a time limit, then write.',
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: 'If the draft starts to drift, go back to the brief, not the blank page. The decision is already made. You just have to follow it.',
    },
  ],
  tags: ['Workflows', 'Systems', 'Owned media'],
};
