// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11pmyl36be3cd0468f · version 3 · da7e0a112d54a3d4
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'internal-links-how-a-site-starts-to-compound',
  title: 'Internal links: how a site starts to compound',
  summary:
    'Internal linking is the cheapest compounding move on a site you own: link new posts back, update old ones forward, and run a checklist every time you publish.',
  category: 'Technology',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "Most sites I see are a pile of posts. Each one was published, shared once, then left on its own. My argument is simple. Internal linking is the cheapest compounding move on a site you own. It isn't an SEO trick. It's a system you run every time you publish.",
    },
    {
      type: 'p',
      text: 'An internal link is a link from one page on your site to another page on your site. It does two jobs. It gives readers somewhere to go next, and it helps search engines find and understand your pages. Neither job costs anything except a few minutes of attention.',
    },
    {
      type: 'h2',
      text: 'A pile of posts is not a body of work',
      id: 'a-pile-of-posts-is-not-a-body-of-work',
    },
    {
      type: 'p',
      text: 'The rule is simple. Every new post should link back to older ones. Older ones should be updated to link forward to the new one. Do that every time and separate posts turn into a connected body of work.',
    },
    {
      type: 'p',
      text: "This builds on something I believe firmly. The site you own is the asset that compounds. I've argued that [your own website is the home and social platforms are the megaphone](/blog/own-the-house-rent-the-megaphone). Links are the wiring of that house. Without them, you have a set of rooms with no doors between them.",
    },
    {
      type: 'p',
      text: 'This is Part 5 of the publishing system series. It\'s the "Ship" stage. It follows the content brief, writing with AI without losing your voice, and the SEO checks I actually run. Those parts help you make one good post. This part makes each post help the others.',
    },
    {
      type: 'h2',
      text: 'Why links make a site compound',
      id: 'why-links-make-a-site-compound',
    },
    {
      type: 'p',
      text: 'Google is clear about why links matter. In its [link best practices](https://developers.google.com/search/docs/crawling-indexing/links-crawlable?hl=zh-tw), it says it treats links as a signal when judging how relevant a page is. It also uses them to find new pages to crawl. The same guidance says every important page on your site should be linked from at least one other page on the site.',
    },
    {
      type: 'p',
      text: "That's the search engine side. The reader side matters just as much, and here I'm giving my opinion. A reader who finishes a post and finds a clear next step keeps reading. A post with no onward links is a dead end. They close the tab and you've lost them.",
    },
    {
      type: 'p',
      text: "I think of internal links as distribution inside your own site. I've written that [how something spreads is part of the product, not an afterthought](/blog/distribution-is-part-of-the-product). That applies inside your site as well as outside it. Each link is a path someone can take.",
    },
    {
      type: 'p',
      text: 'This is how the compounding works. A new post linked in both directions adds value to the old posts, because they now lead somewhere fresh. Each old post you update sends its readers forward to newer work. Nothing here needs a big budget or a technical audit. It just needs doing, every time.',
    },
    {
      type: 'h3',
      text: 'Anchor text: say where the link goes',
      id: 'anchor-text-say-where-the-link-goes',
    },
    {
      type: 'p',
      text: "Anchor text is the visible, clickable text of a link. Google's guidance says good anchor text is [descriptive, reasonably concise and relevant](https://developers.google.com/search/docs/crawling-indexing/links-crawlable?hl=zh-tw) to both the page it sits on and the page it points to.",
    },
    {
      type: 'p',
      text: 'That\'s why "click here", "read more" and "this article" are wasted links. Google\'s page uses exactly these kinds of phrases as examples of anchors that are too vague. They tell neither the reader nor Google what\'s on the other side.',
    },
    {
      type: 'p',
      text: "Don't swing the other way and stuff keywords into anchors either. The same page warns that keyword stuffing breaches Google's spam policies. My test is simple: does the reader need these words to know where they're going? If not, cut them.",
    },
    {
      type: 'p',
      text: "Context matters as much as the anchor. The sentence around a link should explain why it's there. Google's guidance also advises against putting several links side by side, because readers can't tell them apart. Every internal link in this piece tries to follow that rule.",
    },
    {
      type: 'h3',
      text: 'Make links crawlable',
      id: 'make-links-crawlable',
    },
    {
      type: 'p',
      text: 'A short note for builders. Google says it can generally only crawl links that are <a> elements with an href attribute. Links that only work through script events may not be picked up ([source](https://developers.google.com/search/docs/crawling-indexing/links-crawlable?hl=zh-tw)).',
    },
    {
      type: 'code',
      code: '<!-- Crawlable -->\n<a href="/blog/systems-beat-motivation">turning a messy process into a system</a>\n\n<!-- Risky -->\n<span onclick="goto(\'/blog/systems-beat-motivation\')">read more</span>',
      lang: 'html',
    },
    {
      type: 'p',
      text: "If your CMS or framework builds links with JavaScript, check that they render as real <a href> links. That's all I'll say on technical checks here, because they belong to the SEO part of this series.",
    },
    {
      type: 'h2',
      text: 'Link in both directions',
      id: 'link-in-both-directions',
    },
    {
      type: 'p',
      text: "New to old. When you publish, link to two or three older related posts where they genuinely help the reader. That number is my opinion, not a rule. It's enough to give readers somewhere to go without burying the post in links.",
    },
    {
      type: 'p',
      text: "Old to new. Go back to the older posts most related to the new one. Add a forward link inside a sentence where it fits. In my experience this is the step people skip, and it's where the compounding happens. Without it, your older posts keep their traffic and pass none of it on to your new work.",
    },
    {
      type: 'p',
      text: "How many links per post? I don't think there's a magic number. Link where it helps the reader understand something or go further. Stop when you notice you're forcing it.",
    },
    {
      type: 'p',
      text: 'AI can help here. Give it your archive and a new draft, and it can suggest candidates for links. Then you decide which ones to use. I treat it the way I treat AI everywhere: [as a teammate I brief and review, not a vending machine](/blog/ai-is-a-teammate-not-a-vending-machine). A bad link suggestion accepted without checking is worse than no link at all.',
    },
    {
      type: 'h2',
      text: 'Pick a few hub pages',
      id: 'pick-a-few-hub-pages',
    },
    {
      type: 'p',
      text: 'Not every page is equal. Choose a small number of hub pages: the pages that explain what you stand for, or the ones you most want readers to reach. In topic-cluster terms, these are your pillar pages.',
    },
    {
      type: 'p',
      text: "This is how I'd pick them:",
    },
    {
      type: 'list',
      items: [
        "The pages you'd send a brand-new reader to first.",
        'The pages tied to what you sell or build.',
        'Series overviews and topic round-ups.',
      ],
    },
    {
      type: 'p',
      text: 'Related posts in a cluster should link up to their hub. The hub should link down to them. This series is itself a cluster, and each part should lead into the others.',
    },
    {
      type: 'h3',
      text: 'Orphan pages: the quiet leak',
      id: 'orphan-pages-the-quiet-leak',
    },
    {
      type: 'p',
      text: "An orphan page is a page that no other page on your site links to. It goes against Google's guidance that every important page should be linked from at least one other page. Readers can't stumble on it either. It's there, but almost nobody will find it.",
    },
    {
      type: 'p',
      text: 'The fix is a habit. Never publish without at least one inbound link from an existing page. Then check for orphans during your regular review.',
    },
    {
      type: 'h2',
      text: 'The routine: a checklist you can run every time',
      id: 'the-routine-a-checklist-you-can-run-every-time',
    },
    {
      type: 'p',
      text: "A one-off clean-up feels productive, then the pile grows again. What lasts is a routine. It's the same idea behind [turning a messy, repeating task into a system that runs itself](/blog/systems-beat-motivation). Motivation gets you through one afternoon of fixing links. A checklist gets you through every post you publish.",
    },
    {
      type: 'callout',
      title: 'Internal linking checklist',
      text: 'At publish: 1. Link back to two or three related older posts (my default, not a rule). 2. Link up to the relevant hub page. 3. Use descriptive anchors with a sentence of context around each one. 4. Confirm at least one existing page links to the new post. 5. Check that links render as real <a href> links. Straight after: 6. Open the most related older posts and add a forward link to the new one, inside a sentence where it fits. On a regular review, at whatever pace suits you: 7. Look for orphan pages with no inbound links. 8. Replace vague anchors like "click here" and "read more". 9. Make sure each hub links to its newer cluster posts.',
      tone: 'build',
    },
    {
      type: 'p',
      text: 'The final part of this series, "Publish, measure, repeat", closes the loop. It covers what to look at once the post is live and how to turn that into your next brief.',
    },
    {
      type: 'h2',
      text: 'Do this today',
      id: 'do-this-today',
    },
    {
      type: 'p',
      text: "Don't wait for a site-wide audit. Start with one post.",
    },
    {
      type: 'list',
      items: [
        'Open your most recent post.',
        'Add descriptive links to two or three older posts it genuinely relates to.',
        'Open each of those older posts and add a forward link to the new one, in a sentence where it belongs.',
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: 'Twenty minutes, maybe less. Do it every time you publish, and your site stops being a pile and starts to compound.',
    },
  ],
  tags: ['Owned media', 'Systems', 'Checklist'],
};
