// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11pmyv74cd61228008 · version 5 · d4b5580c94baa763
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'publish-measure-repeat',
  title: 'Publish, measure, repeat: closing the loop',
  summary:
    'How to measure content performance on a small site: what to check at a week, a month and a quarter, and a 30-minute weekly routine to turn data into briefs.',
  category: 'Automation',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "Most founders measure content like they're waiting for a grade. They hit publish, refresh the analytics, see a small number and feel judged. I think that's the wrong way to use measurement. Measuring content performance isn't there to grade you. It's there to give you what you need for your next brief.",
    },
    {
      type: 'p',
      text: "This is the last part of the series. Research, briefs, writing with AI, the SEO checks and internal links all go into the system. Measurement is how the system learns. Without it you're just publishing on repeat and hoping.",
    },
    {
      type: 'h2',
      text: 'Measurement is not a report card',
      id: 'measurement-is-not-a-report-card',
    },
    {
      type: 'p',
      text: "On a small site the numbers are tiny and noisy. Say a post gets eleven visits one week and four the next. That doesn't prove anything. It hints at something, and it gives you a direction.",
    },
    {
      type: 'p',
      text: "That's fine. You're not trying to prove anything. You're trying to decide what to do next.",
    },
    {
      type: 'p',
      text: "So is it worth measuring when you only get a few dozen visits a week? Yes. It works if you watch fewer things, on a fixed schedule, and read them for direction rather than proof. One query you didn't expect or one reply from a reader is enough to change your next piece.",
    },
    {
      type: 'p',
      text: "This is also why it matters that the posts live on your own site. Data from a site you own is yours to read, keep and act on. It's a big part of why I say [own the house and rent the megaphone](/blog/own-the-house-rent-the-megaphone). A platform shows you whatever it decides to show you. Your site shows you everything.",
    },
    {
      type: 'h2',
      text: 'Why fewer metrics on a schedule beat a dashboard',
      id: 'why-fewer-metrics-on-a-schedule-beat-a-dashboard',
    },
    {
      type: 'p',
      text: 'Dashboards make you want to keep checking, but they rarely tell you what to do. Check every day and the noise starts setting your mood. A good Tuesday makes you smug and a quiet Thursday makes you rethink the whole strategy. Neither one tells you anything.',
    },
    {
      type: 'p',
      text: "A fixed schedule fixes that. It's the same principle as any other repeating task. You don't depend on willpower or curiosity, you depend on a routine that runs whether you feel like it or not. I've written about [turning messy processes into systems that run themselves](/blog/systems-beat-motivation), and measurement is a good candidate for that treatment.",
    },
    {
      type: 'p',
      text: "Here's what I actually look at:",
    },
    {
      type: 'list',
      items: [
        'Search Console impressions and clicks per post. Is the page being shown, and is anyone choosing it?',
        'The queries each page appears for. For me this is the most useful number on a small site, because it shows what people were actually asking.',
        'Visits to the page. A rough sense of whether anyone is arriving at all.',
        'One action signal per post. Pick the one thing the post was meant to cause, like a reply, a sign-up or an enquiry, and track that.',
      ],
    },
    {
      type: 'p',
      text: "Here's what I ignore at this size:",
    },
    {
      type: 'list',
      items: [
        'Day-to-day swings.',
        'Sitewide totals, which blur good posts and dead ones into one meaningless line.',
        'Time on page and bounce rate. At low volume I find them very easy to over-read and rarely useful to act on.',
      ],
    },
    {
      type: 'p',
      text: "One more rule: no benchmarks. Don't compare your post with an industry average you found in a thread somewhere. Compare it with how it did before, and with your other posts. That's the only comparison that tells you anything about your site.",
    },
    {
      type: 'h3',
      text: "Signals that aren't traffic",
      id: 'signals-that-aren-t-traffic',
    },
    {
      type: 'p',
      text: 'Some of the best signals never appear in analytics. A reader replies to your newsletter. Someone signs up or sends an enquiry. A post gets shared, or a person quotes it back to you on a call.',
    },
    {
      type: 'p',
      text: 'On a small site these often show up before search traffic does, and in my experience they tell you more. Ten visits and one thoughtful reply beat a hundred visits and silence.',
    },
    {
      type: 'p',
      text: "It's also a reminder that search is only one route. How a post spreads matters as much as how it ranks. [Distribution is part of the product](/blog/distribution-is-part-of-the-product), so measure the spread, not just the ranking.",
    },
    {
      type: 'h2',
      text: 'What to check at a week, a month and a quarter',
      id: 'what-to-check-at-a-week-a-month-and-a-quarter',
    },
    {
      type: 'p',
      text: "These time frames are my opinion. They're not rules about how search engines behave. They're the rhythm I find useful, and you should adjust them to your site.",
    },
    {
      type: 'p',
      text: "After one week, check the basics. Is the post indexed? Did the internal links go in? Did the distribution actually go out? Did anyone reply or react? It's too early to judge search performance, so don't try.",
    },
    {
      type: 'p',
      text: 'After one month, look at the queries. Which searches is the post showing up for? Do they match the question you set out to answer in the brief? Write down anything that surprises you. Surprises are often where the next post comes from.',
    },
    {
      type: 'p',
      text: "After one quarter, I think it's fair to decide whether a post is a dud or just slow. Look at the trend, not the total. Is it going up, staying flat or not showing up at all?",
    },
    {
      type: 'p',
      text: "A slow starter usually shows up for the right queries in small numbers and is slowly moving up. A dud either doesn't show up at all or shows up for queries that have nothing to do with what you wrote. Judge it on how well it fits the intent and which way it's heading. The raw count matters less.",
    },
    {
      type: 'h3',
      text: 'Impressions without clicks',
      id: 'impressions-without-clicks',
    },
    {
      type: 'p',
      text: 'This one confuses people. A post shows plenty of impressions in Search Console and almost no clicks.',
    },
    {
      type: 'p',
      text: "My working diagnosis is one of two things. The page is being shown for a query, but the title and description don't make anyone want to click. Or the query isn't quite what the page is about, so searchers scroll past.",
    },
    {
      type: 'p',
      text: "What I'd try first is to look at the queries the page is actually showing up for. Rewrite the title and description to answer that query plainly. If the query is close but not quite right, tighten the page so it fits that intent better. Then wait and see. Treat it as a guess to test. It might not work.",
    },
    {
      type: 'h2',
      text: 'Turn every finding into one action',
      id: 'turn-every-finding-into-one-action',
    },
    {
      type: 'p',
      text: 'A finding with no action is just trivia. Every time I review a post, it gets exactly one of four moves:',
    },
    {
      type: 'list',
      items: [
        'Refresh when the page shows up for the right question but answers it thinly or is out of date.',
        'Add internal links when the page is good but isolated. Point newer and related posts at it.',
        "Write a follow-up when the queries show a related question the post doesn't answer.",
        "Leave it alone when it's too early or the signal is too weak to act on.",
      ],
    },
    {
      type: 'p',
      text: "Leaving it alone counts as a decision. Most posts, most weeks, should get exactly that. Fiddling with a page because you feel anxious isn't a strategy.",
    },
    {
      type: 'p',
      text: "Bigger changes follow the same logic. Merge two posts when they compete for the same question. Retire a post when it no longer serves anyone. Update it, don't rewrite it, when the core is sound and only the details have aged. Writing a new post is often the least useful option when an old one is nearly there.",
    },
    {
      type: 'h2',
      text: 'From notes to the next brief',
      id: 'from-notes-to-the-next-brief',
    },
    {
      type: 'p',
      text: "All of this goes into one running notes file. Each entry has four parts: the post, the date checked, what you saw and what you'll do. One line per post. Nothing fancy.",
    },
    {
      type: 'p',
      text: "This file is where your next briefs come from. The queries people actually typed become the reader's question. Their replies become the angle. You stop guessing what to write because readers are already telling you.",
    },
    {
      type: 'p',
      text: "Once a month, hand the file to AI and ask it to group the notes into candidate briefs. Then review them yourself, because the summary is a draft, not a decision. It's the same way I [work with AI as a teammate rather than a vending machine](/blog/ai-is-a-teammate-not-a-vending-machine): brief it, then review what comes back.",
    },
    {
      type: 'p',
      text: "And don't wait for perfect data before you publish the next piece. You'll never have it on a small site. Ship the next post and let it teach you something too.",
    },
    {
      type: 'h2',
      text: 'The 30-minute weekly routine',
      id: 'the-30-minute-weekly-routine',
    },
    {
      type: 'callout',
      title: 'Small numbers are still signal',
      text: "One reply or one new query is information. Write it down and don't over-read it. Over a few months those small notes add up to a clear picture of what your readers want.",
      tone: 'signal',
    },
    {
      type: 'p',
      text: "Here's the whole loop in half an hour a week:",
    },
    {
      type: 'list',
      items: [
        'Publish. Publish or schedule one piece. Run the SEO and internal link checks from earlier in this series.',
        'Check. Open Search Console for any post at its one-week, one-month or one-quarter mark. Check replies, sign-ups and enquiries.',
        'Note. Write one line per post in the notes file, with one action next to it: refresh, link, follow up or leave alone.',
        "Brief. Turn the strongest finding into next week's brief.",
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: "That's the system: publish, measure, repeat.",
    },
    {
      type: 'p',
      text: "This week, put 30 minutes in your calendar. Create the notes file with four columns: post, date, what you saw, what you'll do. Then run the loop once with the posts you already have. You don't need more traffic to start. You just need to start paying attention on a schedule.",
    },
  ],
  tags: ['Systems', 'Workflows', 'Marketing'],
};
