// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11juk44a74633598cf · version 6 · 74f25d8ff9c28e0f
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'publishing-system-not-content-calendar',
  title: 'Your website needs a publishing system, not a calendar',
  summary:
    "A content calendar only tells you when to publish; a publishing system decides, checks, ships and learns, and here's a four-question audit to find your gap.",
  category: 'Founder notes',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "A content calendar tells you when to publish. That's all it does. A publishing system decides what to publish, checks it against clear standards, ships it the same way every time, and feeds what it learns into the next round. If you keep missing your own schedule, I don't think the schedule is the problem. The rest of the process is missing.",
    },
    {
      type: 'h2',
      text: 'A calendar answers one question. A system answers four',
      id: 'a-calendar-answers-one-question-a-system-answers-four',
    },
    {
      type: 'p',
      text: "Here's how I define a publishing system: decide, check, ship, learn.",
    },
    {
      type: 'list',
      items: [
        "Decide what to write and why it's worth writing.",
        'Check the draft against standards you can actually tick off.',
        "Ship it along a path that's the same every time.",
        'Learn from how it did, and let that shape what comes next.',
      ],
    },
    {
      type: 'p',
      text: "A calendar is one small input to this. It's a useful one, because a date creates a bit of pressure. But a date can't tell you what to write, whether the draft is good enough or what to do differently next time. Treating the calendar as the whole process is like treating a deadline as a project plan.",
    },
    {
      type: 'h2',
      text: 'Why content calendars fall apart after a few weeks',
      id: 'why-content-calendars-fall-apart-after-a-few-weeks',
    },
    {
      type: 'p',
      text: 'A calendar runs on motivation. It fills in the "when" and leaves every hard decision for the day you sit down to write: the topic, the angle, the sources, whether it\'s ready. That\'s a lot to decide in one sitting, every single time.',
    },
    {
      type: 'p',
      text: "I've written before about why [systems beat motivation](/blog/systems-beat-motivation). Motivation gets you started. It can't keep the engine running. A calendar is a motivation-powered tool pretending to be a system.",
    },
    {
      type: 'p',
      text: "Then the empty slots turn into guilt, and the guilt turns into skipped weeks. My view is that most founders don't stop publishing because they've run out of ideas. They stop because every post starts from zero. A blank page on a Tuesday evening loses to almost anything else on your list.",
    },
    {
      type: 'p',
      text: "There's a quieter problem too. A calendar has no idea whether last month's posts were worth publishing. So it can't get better. It keeps repeating the same cycle until one day it just stops.",
    },
    {
      type: 'h2',
      text: 'What a publishing system actually decides, checks and ships',
      id: 'what-a-publishing-system-actually-decides-checks-and-ships',
    },
    {
      type: 'p',
      text: "This is the outline. Each stage gets its own part later in the series, so here I'm only sketching the shape.",
    },
    {
      type: 'h3',
      text: 'Decide: research that turns into briefs',
      id: 'decide-research-that-turns-into-briefs',
    },
    {
      type: 'p',
      text: "Topics should come from what your audience is actually asking and what your site already covers. They shouldn't come from whatever you fancy on the day.",
    },
    {
      type: 'p',
      text: "What this stage produces is a brief: the reader's question, your angle and the sources you'll lean on. Once that exists, writing gets much easier, because nobody starts from a blank page. You're answering a question you've already framed.",
    },
    {
      type: 'h3',
      text: 'Check: standards you can tick off',
      id: 'check-standards-you-can-tick-off',
    },
    {
      type: 'p',
      text: '"Is it good enough?" should have an answer. It shouldn\'t be a feeling. That means written checks for voice, facts, SEO basics and internal links.',
    },
    {
      type: 'p',
      text: 'Google\'s guidance on [people-first content](https://developers.google.com/search/docs/fundamentals/creating-helpful-content) is a good place to borrow from. It asks whether content offers original information, research or analysis. It asks whether it shows first-hand expertise. And it flags producing "lots of content on many different topics in hopes that some of it might perform well in search results" as a warning sign. A good system builds those questions into its checks, so you\'re asking them every time and not only when you remember.',
    },
    {
      type: 'p',
      text: "The same page says plainly that Google has no preferred word count. So your standards should be about whether the piece is useful. Hitting a length isn't a standard.",
    },
    {
      type: 'callout',
      title: 'A standard is something you can fail',
      text: '"Make it good" is not a standard. "Every factual claim links to a source" is. If a draft can\'t fail a check, the check isn\'t doing anything.',
      tone: 'build',
    },
    {
      type: 'h3',
      text: 'Ship: a repeatable path to live',
      id: 'ship-a-repeatable-path-to-live',
    },
    {
      type: 'p',
      text: "Use the same steps every time, from draft to live page. Who formats it, where it goes, what gets added before it's published. Every step you've already decided is one fewer place to stall.",
    },
    {
      type: 'p',
      text: "This is also where you choose shipping over polishing. A post that's live and decent is worth more than a perfect one sitting in drafts.",
    },
    {
      type: 'h3',
      text: 'Learn: close the loop',
      id: 'learn-close-the-loop',
    },
    {
      type: 'p',
      text: "Look at what each post did, then let that shape the next round of decisions. Calendars leave this step out completely. To me it's the most important one, because it's what makes a system improve over time. Without it you're just publishing on repeat.",
    },
    {
      type: 'h2',
      text: 'Where AI fits without making you sound like everyone else',
      id: 'where-ai-fits-without-making-you-sound-like-everyone-else',
    },
    {
      type: 'p',
      text: "AI is very good at the middle of the process: drafting from a brief, checking a draft against a checklist, suggesting where to add links. It's poor at the decisions only you can make, like what you believe, what you've seen first-hand, and which angle is worth taking.",
    },
    {
      type: 'p',
      text: "When output sounds generic, the brief was usually generic too. Give it your voice rules, your sources and your angle. Then review what comes back the way you'd review a teammate's work. That's the whole argument of [AI is a teammate, not a vending machine](/blog/ai-is-a-teammate-not-a-vending-machine), and it matters more inside a publishing process than almost anywhere else.",
    },
    {
      type: 'p',
      text: "Google's guidance makes the same point from the other side. It lists \"using extensive automation to produce content on many topics\" as a warning sign. A publishing system isn't there to take people out of the loop. It's there so a person stays in charge of what gets said, while the repetitive work gets faster.",
    },
    {
      type: 'h2',
      text: 'Why this matters more on a site you own',
      id: 'why-this-matters-more-on-a-site-you-own',
    },
    {
      type: 'p',
      text: "Your website is the house you own. Social platforms are the megaphone you rent. I've made that case in [own the house, rent the megaphone](/blog/own-the-house-rent-the-megaphone), and a publishing system is how you keep building the house rather than just shouting from a rented stage.",
    },
    {
      type: 'p',
      text: "A post on your own site keeps working after it goes out. You can link to it, update it and build on it. If you add to it every week with a system, you're building an asset. Without one, you're feeding a stream.",
    },
    {
      type: 'p',
      text: "To be clear, this is my opinion and not a promised result. I think compounding comes from consistency plus connection: posts that link to each other, cover a focused set of topics and get better over time. Volume on its own doesn't do it. A hundred unconnected posts is a pile. Twenty well-linked ones on a clear theme is a body of work.",
    },
    {
      type: 'h2',
      text: 'Is your process a system or just a schedule?',
      id: 'is-your-process-a-system-or-just-a-schedule',
    },
    {
      type: 'p',
      text: 'Ask yourself four questions:',
    },
    {
      type: 'list',
      items: [
        'Do you know your next three topics, and why you chose them?',
        'Do you have written standards a draft has to pass before it goes live?',
        'Is the path from draft to live page the same every time?',
        'Do you look back at what worked before you plan the next post?',
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: "If you answered no to most of them, you have a schedule. That's fine. Most people start there. It just isn't a system yet.",
    },
    {
      type: 'h2',
      text: 'What to do this week',
      id: 'what-to-do-this-week',
    },
    {
      type: 'p',
      text: 'Open a blank note and write four headings: Decide, Check, Ship, Learn. Under each, write one line describing what you do today. If you do nothing at a stage, write "nothing". Be honest. This is for you.',
    },
    {
      type: 'p',
      text: 'Then fix the weakest stage first, and leave the calendar alone. For most people that means one of two small things:',
    },
    {
      type: 'list',
      items: [
        'A one-page checklist of standards every draft has to pass: voice, facts with sources, a clear title, at least one internal link.',
        "A simple brief template: the reader's question, your angle, your sources. Fill one in before you write anything.",
      ],
    },
    {
      type: 'p',
      text: 'Either takes an hour or less, and either will do more for your consistency than another colour-coded calendar.',
    },
    {
      type: 'p',
      text: "The rest of this series builds out the full system one piece at a time: research that turns into briefs, writing with AI in your own voice, the SEO checks that actually matter, internal links, and measurement that closes the loop. Do the audit now, and you'll know which part to read first.",
    },
  ],
  tags: ['Systems', 'Owned media', 'Workflows'],
};
