// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11pmyge5bab93b3c04 · version 5 · 2c45cab651da3994
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'seo-without-the-theatre',
  title: 'SEO without the theatre',
  summary:
    'My pre-publish SEO checklist: six checks for title, description, headings, links, indexability and usefulness, with none of the keyword-density theatre.',
  category: 'Marketing',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "SEO for your own site is not a dark art. It's a short quality check you run before you publish. Most of the advice out there is ritual: numbers to hit, scores to turn green and promises nobody can keep. I keep a different list. It has six checks I can verify myself without buying any tools. The title, the description, the headings, the links, whether the page can be found at all, and whether the page actually helps the person reading it.",
    },
    {
      type: 'p',
      text: "None of these will guarantee a ranking. Nothing will, and I'm not going to pretend otherwise. What they do is stop me shipping a post with an obvious flaw.",
    },
    {
      type: 'h2',
      text: 'Checkable or folklore?',
      id: 'checkable-or-folklore',
    },
    {
      type: 'p',
      text: 'I sort SEO advice into two piles.',
    },
    {
      type: 'p',
      text: "Checkable: a clear title, an honest description, headings that make sense, internal links that say where they go, a page that can be crawled and indexed, and content that answers a real person's question.",
    },
    {
      type: 'p',
      text: 'Folklore: keyword density, magic word counts, plugin scores and anyone promising you a position.',
    },
    {
      type: 'p',
      text: 'The first pile goes into my process. The second pile I ignore.',
    },
    {
      type: 'p',
      text: "This is the Check step in the series. The brief came first, then the draft. Now we check the draft before it goes live. It's also worth remembering why this matters at all. SEO is only worth doing because you're building on a house you own. That idea is the heart of [own the house, rent the megaphone](/blog/own-the-house-rent-the-megaphone). Search sends people to your house. These checks make sure the door is open and the sign on it is accurate.",
    },
    {
      type: 'h2',
      text: 'The checks that actually matter',
      id: 'the-checks-that-actually-matter',
    },
    {
      type: 'p',
      text: "Each check is a question you can answer yes or no before you hit publish. That's the difference between a check and an opinion.",
    },
    {
      type: 'h3',
      text: 'A title that says what the page is',
      id: 'a-title-that-says-what-the-page-is',
    },
    {
      type: 'p',
      text: "Google's documentation says the title link is [often the primary piece of information people use to decide which result to click](https://developers.google.com/search/docs/appearance/title-link). It advises a <title> on every page, with text that's descriptive and concise. Each title should be distinct from your other pages. It warns against keyword stuffing and boilerplate.",
    },
    {
      type: 'p',
      text: "On length, the same page says [there's no limit on how long a <title> element can be](https://developers.google.com/search/docs/appearance/title-link), but the title link gets truncated as needed to fit the device width. So length is about how the title displays. It is not a ranking rule.",
    },
    {
      type: 'p',
      text: 'Every title on this site gets " — Shimanto" added to the end, so a shorter title leaves room for it. Treat a target like 50 characters as a display preference, not an SEO law.',
    },
    {
      type: 'p',
      text: "One more check: the headline people see on the page and the <title> element should agree. Google's docs give the example of [a page titled for 2020 while the visible headline says 2021](https://developers.google.com/search/docs/appearance/title-link). Google may pick a different title for the search result when they don't match. Fixing it takes seconds if you look.",
    },
    {
      type: 'h3',
      text: "A description that's honest, not bait",
      id: 'a-description-that-s-honest-not-bait',
    },
    {
      type: 'p',
      text: "According to Google, [snippets are primarily created from the page content itself](https://developers.google.com/search/docs/appearance/snippet). It sometimes uses the meta description if that gives a more accurate description of the page. I don't treat the description as a ranking lever. I treat it as my pitch to someone scanning a page of results.",
    },
    {
      type: 'p',
      text: "Write a unique one for every page. Google's guidance says [identical or similar descriptions on every page aren't helpful](https://developers.google.com/search/docs/appearance/snippet) when individual pages show up in search. Its examples of bad descriptions are a list of keywords, one description reused everywhere, and a description that doesn't summarise the page.",
    },
    {
      type: 'p',
      text: "As with titles, Google says [there's no limit on how long a meta description can be](https://developers.google.com/search/docs/appearance/snippet), but snippets get truncated to fit the device width. A range like 120–160 characters is a sensible display target, nothing more.",
    },
    {
      type: 'p',
      text: "On this site the article's dek is the meta description, so writing one writes both. And if you can't summarise the post honestly in two sentences, that tells you something about the post.",
    },
    {
      type: 'h3',
      text: 'Headings that form an outline',
      id: 'headings-that-form-an-outline',
    },
    {
      type: 'p',
      text: "One H1, which is the page title. H2s for the main sections. H3s inside them. Don't skip levels, and don't use a heading just because you want big bold text.",
    },
    {
      type: 'p',
      text: "To me, this is about readability and structure more than ranking. The test is simple. Read only the headings. Do they tell the story of the piece? If they don't, fix the structure, not the keywords.",
    },
    {
      type: 'h3',
      text: 'Internal links with descriptive anchors',
      id: 'internal-links-with-descriptive-anchors',
    },
    {
      type: 'p',
      text: 'Every post should link to a few related pages on your own site. The link text should say where it goes. "Click here" tells the reader nothing.',
    },
    {
      type: 'p',
      text: "The check takes two questions. Does this post link to at least one older piece? Can at least one older piece now link back to it? The next part of the series covers internal linking properly, so I'll leave it there.",
    },
    {
      type: 'h3',
      text: 'A page that can be found at all',
      id: 'a-page-that-can-be-found-at-all',
    },
    {
      type: 'p',
      text: 'This is the least glamorous check and the most important one. Before I call a post done, I confirm:',
    },
    {
      type: 'list',
      items: [
        "It's published, not sitting in drafts or behind a preview link.",
        "It's in the sitemap.",
        "It isn't blocked by a noindex tag or a robots rule I forgot about.",
        'At least one other page on the site links to it.',
      ],
    },
    {
      type: 'p',
      text: 'A brilliant post nobody can reach is just a private document.',
    },
    {
      type: 'h3',
      text: 'Content that answers a real person',
      id: 'content-that-answers-a-real-person',
    },
    {
      type: 'p',
      text: 'This is my working definition of "people-first", and it\'s my opinion rather than a quoted guideline. Name the reader\'s question. Answer it early and plainly. Cut anything you wrote only for a search engine.',
    },
    {
      type: 'p',
      text: "This is where the brief pays off. If the brief named the reader's question, this check is easy: did the post answer it? If you have to scroll to find the answer, the post isn't done.",
    },
    {
      type: 'h2',
      text: 'The theatre you can safely skip',
      id: 'the-theatre-you-can-safely-skip',
    },
    {
      type: 'p',
      text: "Keyword density. Google's title guidance warns that keyword stuffing [can make your results look spammy to Google and to users](https://developers.google.com/search/docs/appearance/title-link). Beyond that, I don't count keywords. I check that the topic is named plainly, in words my reader would actually use.",
    },
    {
      type: 'p',
      text: 'Magic word counts. The right length is however long it takes to answer the question well. A tight 700 words beats a padded 3,000 every time.',
    },
    {
      type: 'p',
      text: "Plugin scores and green lights. A score measures how well you followed the plugin's checklist. It says nothing about whether the reader was satisfied, and it can't tell you a page will rank. I treat it as a reminder at best.",
    },
    {
      type: 'p',
      text: "Ranking promises. Anyone guaranteeing positions is selling theatre. Nobody controls search results except the search engine. The honest offer is a page that's clear, findable and useful.",
    },
    {
      type: 'h2',
      text: 'Make it a step, not a ritual',
      id: 'make-it-a-step-not-a-ritual',
    },
    {
      type: 'p',
      text: "The value isn't in any single check. It's in running all of them the same way every time. That's the argument from [systems beat motivation](/blog/systems-beat-motivation): turn a repeating task into a step that runs whether or not you feel like it.",
    },
    {
      type: 'p',
      text: "So the check sits in one fixed place in my workflow. It comes after the draft and before publish, every time. It's short on purpose. If a check takes an hour, you'll skip it on the week you're busy. If it takes ten minutes, you won't.",
    },
    {
      type: 'p',
      text: "And it's a checklist, not a quest for perfection. Same principle as [shipping the ugly version](/blog/ship-the-ugly-version): a checked, published post is worth more than a perfect one sitting in drafts.",
    },
    {
      type: 'h2',
      text: 'Copy this pre-publish SEO checklist',
      id: 'copy-this-pre-publish-seo-checklist',
    },
    {
      type: 'callout',
      title: 'Pre-publish SEO checklist',
      text: "1. Title: descriptive, distinct from my other pages, and matches the visible headline. 2. Description: unique, and an honest summary of this page. 3. Headings: one H1, then logical H2s and H3s. Reading the headings alone tells the story. 4. Links: at least one descriptive internal link out, and one older post now linking back in. 5. Findable: published, in the sitemap, not noindexed and reachable from another page. 6. Useful: the reader's question is answered early and plainly.",
      tone: 'build',
    },
    {
      type: 'p',
      text: 'Paste that list into your publishing workflow today, wherever your drafts live, and run it on your next post. It should take about ten minutes.',
    },
    {
      type: 'p',
      text: 'Check four on that list is where things start to add up. Next in the series: internal links, and how a site starts to compound.',
    },
  ],
  tags: ['Checklist', 'Workflows', 'Marketing'],
};
