// Generated by Publishing OS. Do not edit by hand: changes are overwritten when this post is republished.
// content ci_mv11pmybbc757a517a07 · version 3 · f88fe78549be3ed1
import type { Entry } from '../../catalog';

export const post: Entry = {
  slug: 'writing-with-ai-without-losing-your-voice',
  title: 'Writing with AI without losing your voice',
  summary:
    'Generic AI copy comes from generic input. Keep your voice when writing with AI using three levers: a voice file, a tight brief and a review pass with teeth.',
  category: 'AI',
  publishedAt: '2026-10-09',
  body: [
    {
      type: 'p',
      text: "If your AI drafts sound bland, the problem is usually the input, not the model. A better model won't fix a vague request. Staying away from AI won't protect your voice either. What protects it is three things you control: written voice rules, a tight brief and a review pass with teeth.",
    },
    {
      type: 'p',
      text: "This is the writing side of the publishing system. The last part turned a reader's question into a brief. This part covers what that brief and the documents around it need to carry so the draft comes back sounding like you. I covered the mindset in [AI is a teammate, not a vending machine](/blog/ai-is-a-teammate-not-a-vending-machine). This piece is about the actual documents.",
    },
    {
      type: 'h2',
      text: 'Generic in, generic out',
      id: 'generic-in-generic-out',
    },
    {
      type: 'p',
      text: "This part is my opinion, and I'll label it that way. A model is only guessing at your voice from the words you give it. Give it a topic and nothing else, and it fills the gaps with the most likely sentence. The most likely sentence is the average of everyone. That's why the output reads like nobody wrote it.",
    },
    {
      type: 'p',
      text: 'So "how do I make AI sound like me?" is really a different question: "what have I written down about how I sound?" For most founders the honest answer is nothing. The voice is in their head. Nothing in their head reaches the model.',
    },
    {
      type: 'h2',
      text: 'Lever one: a voice file the model can actually follow',
      id: 'lever-one-a-voice-file-the-model-can-actually-follow',
    },
    {
      type: 'p',
      text: 'A model can\'t follow taste. It can follow rules. "Sound like me" isn\'t an instruction. "Short declarative sentences" is.',
    },
    {
      type: 'p',
      text: "Keep the file to one page. If it's longer, nobody uses it, and that includes the model.",
    },
    {
      type: 'h3',
      text: 'What goes in it',
      id: 'what-goes-in-it',
    },
    {
      type: 'list',
      items: [
        "Spelling and format. Which regional spelling, how headings work, and what a page can and can't contain.",
        'Sentence style. Length, person, how much hedging you allow, and whether you give opinions or just summarise.',
        "Banned phrases. A list you add to every week from lines you've had to cut. It's personal. It isn't a generic list of \"AI tells\", and no list of phrases proves something was machine-written. It just records what doesn't sound like you.",
        "Claims policy. What the model may state as fact (only what's in the brief or a cited source) and what it has to leave out or label as opinion.",
        'Ending rule. How every piece finishes.',
      ],
    },
    {
      type: 'h3',
      text: 'A worked example: my own house rules',
      id: 'a-worked-example-my-own-house-rules',
    },
    {
      type: 'p',
      text: "I don't need to make up an example, because I have one. These are the rules this site runs on:",
    },
    {
      type: 'list',
      items: [
        'First person, short declarative sentences, practical and opinionated.',
        'British spelling: standardise, organisation, colour.',
        "No claims about metrics, clients, revenue or events that aren't in the context I provide.",
        'No H1 in the body. Headings, lists, quotes and callouts are fine. No images or tables.',
        'Every piece ends with something the reader can do.',
      ],
    },
    {
      type: 'p',
      text: "Notice that you can check every one of them. I can read a draft and answer yes or no for each rule. Is it British spelling? Did it invent a number? Does it end with an action? A rule you can't check is a wish, and the model treats wishes as optional.",
    },
    {
      type: 'p',
      text: "This matters most on your own site. Social platforms set the format and the feed decides who sees you. Your site is the one place where the voice is fully yours, which is the whole argument of [own the house, rent the megaphone](/blog/own-the-house-rent-the-megaphone). It's worth protecting there first.",
    },
    {
      type: 'h2',
      text: 'Lever two: a brief that carries the angle, not just the topic',
      id: 'lever-two-a-brief-that-carries-the-angle-not-just-the-topic',
    },
    {
      type: 'p',
      text: "A topic gets you a generic post. An angle gets you your post. The brief is where your thinking goes in, so the model isn't left to supply it.",
    },
    {
      type: 'p',
      text: "I won't repeat how to get from a question to a brief. That was the last part. Here are the fields that protect voice and accuracy.",
    },
    {
      type: 'h3',
      text: 'The brief template',
      id: 'the-brief-template',
    },
    {
      type: 'p',
      text: "READER Who they are. What they already know. What they're trying to do.",
    },
    {
      type: 'p',
      text: "ANGLE The one claim this piece argues, in a sentence I'd say out loud.",
    },
    {
      type: 'p',
      text: 'QUESTIONS TO ANSWER',
    },
    {
      type: 'list',
      items: ['The most important question first', '...'],
      ordered: true,
    },
    {
      type: 'p',
      text: 'ALLOWED FACTS AND SOURCES',
    },
    {
      type: 'list',
      items: ['Fact — link', 'Fact — link'],
    },
    {
      type: 'p',
      text: 'Anything not listed here is opinion (labelled) or gets cut.',
    },
    {
      type: 'p',
      text: 'MY RAW MATERIAL Notes, voice-memo transcript, the example only I have.',
    },
    {
      type: 'p',
      text: 'LINKS Exact internal URLs the draft may use. No others.',
    },
    {
      type: 'p',
      text: "OUT OF SCOPE What other pieces already cover. Stay on this one job. Two fields do most of the work. Allowed facts stops the model making things up, because you've told it exactly what it's allowed to know. My raw material is the part AI can't produce for you: the story, the mistake, the specific detail. Leave it empty and the model will invent something plausible to fill the space.",
    },
    {
      type: 'h3',
      text: 'Who writes what',
      id: 'who-writes-what',
    },
    {
      type: 'p',
      text: 'My view: you write the angle, the examples and the verdict. AI can draft the structure, the transitions and the first pass of prose around them.',
    },
    {
      type: 'callout',
      title: 'The one-sentence test',
      text: "If you can't write the angle in one sentence, you're not ready to draft, with or without AI.",
      tone: 'spark',
    },
    {
      type: 'h2',
      text: 'Lever three: a review pass with teeth',
      id: 'lever-three-a-review-pass-with-teeth',
    },
    {
      type: 'p',
      text: "Reviewing isn't skimming. Read the draft line by line against the voice file and the brief. Every line that fails gets cut or rewritten.",
    },
    {
      type: 'p',
      text: "The facts check isn't optional. Google's own [guidance on generative AI content](https://developers.google.com/search/docs/fundamentals/using-gen-ai-content?hl=pt-br) explains that generative models don't retrieve facts. They predict a likely sequence of words, so their output can contain inaccuracies. Google says to fact-check manually and review all AI-generated content before publishing. That includes metadata such as the title element and meta description. The same page warns that using generative AI to produce lots of pages without adding value for users may break its spam policy on scaled content abuse.",
    },
    {
      type: 'p',
      text: 'I read that as a description of the job, not a threat. Review is where the value gets added.',
    },
    {
      type: 'h3',
      text: 'The review checklist',
      id: 'the-review-checklist',
    },
    {
      type: 'list',
      items: [
        "Facts. Every number, name, date and example traces back to the brief or a linked source. If it doesn't, delete it.",
        'Voice. Check each line against the voice file: spelling, sentence length, person, banned phrases.',
        "Genericness test. Could this sentence appear on anyone's blog? If yes, replace it with your own example or cut it.",
        'Angle. Does every section move the one claim forward? Cut sections that just survey the topic.',
        'Metadata. Title length, summary or meta description, and link targets get the same review as the body.',
        'Ending. Does it finish with something the reader can do?',
        'Feed it back. Every line you cut for voice becomes a banned phrase or a new rule.',
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: 'Step seven is what turns this into a system. Each review makes the next draft better, because the file learns what you keep rejecting.',
    },
    {
      type: 'h2',
      text: 'Make it a system, not a mood',
      id: 'make-it-a-system-not-a-mood',
    },
    {
      type: 'p',
      text: "Your voice stays consistent across many posts when you reuse the same three documents. Being in the right frame of mind doesn't do it. That's the core of [systems beat motivation](/blog/systems-beat-motivation): a repeating task stops depending on your energy once it's written down and run the same way each time.",
    },
    {
      type: 'p',
      text: 'In practice:',
    },
    {
      type: 'list',
      items: [
        'Keep the voice file and the brief template in one place.',
        "Paste both into every drafting session. Don't rely on the model to remember them.",
        'Date and version the voice file when a rule changes, so you know which rules a post was written under.',
      ],
    },
    {
      type: 'p',
      text: "None of this needs a new tool. It needs a document you actually reuse. That's the same point as [the five-tool founder](/blog/the-five-tool-founder): most of the leverage comes from connecting tools you already have.",
    },
    {
      type: 'p',
      text: "The SEO checks, internal links and measurement are separate jobs, and they're the next parts of this series. This one is only about making sure the words are yours.",
    },
    {
      type: 'h2',
      text: 'Build your voice file this week',
      id: 'build-your-voice-file-this-week',
    },
    {
      type: 'list',
      items: [
        "Pick three posts you're proud of. Write down the patterns: sentence length, spelling, how you open, how you close.",
        'Turn them into five to ten rules you can check. Add a claims policy and a starter list of banned phrases.',
        'Brief your next post with the template. Fill in the allowed facts and your own example before you open any AI tool.',
        'Draft with AI, then run the checklist. Add every line you cut to the voice file.',
      ],
      ordered: true,
    },
    {
      type: 'p',
      text: 'Do this for four posts. By then the file will have done more for your voice than any prompt.',
    },
  ],
  tags: ['AI', 'Workflows', 'Systems'],
};
